---
- name: Stop services
  service: name={{ item }} state=stopped
  ignore_errors: true
  with_items:
    - evm-watchdog
    - evmserverd
    - rh-postgresql94-postgresql

- name: Wipe away postgresql database data dir
  #shell: rm -rf /var/opt/rh/rh-postgresql94/lib/pgsql/data/*
  file: path=/var/opt/rh/rh-postgresql94/lib/pgsql/data state=absent
  ignore_errors: true

- name: Create postgresql database data dir
  file: path=/var/opt/rh/rh-postgresql94/lib/pgsql/data/ state=directory owner=postgres group=postgres mode=0700

- name: Init database
  command: appliance_console_cli --region 0 --internal --password smartvm

- name: Stop services
  service: name={{ item }} state=stopped
  ignore_errors: true
  with_items:
    - evm-watchdog
    - evmserverd
    
- name: Restart vmdb
  service: name=rh-postgresql94-postgresql state=restarted

- name: Drop existing vmdb
  postgresql_db: name=vmdb_production state=absent

- name: Create vmdb
  postgresql_db: name=vmdb_production state=present

- name: Extract out db dump
  unarchive: src={{ db_dump }} dest=/tmp

- name: Restore db dump
  shell: psql vmdb_production < /tmp/db.sql

- name: Copy files
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: v2_key, dest: "{{ vmdb_root }}/certs" }
    - { src: REGION, dest: "{{ vmdb_root }}" }
    - { src: GUID, dest: "{{ vmdb_root }}" }

- name: Start services
  service: name={{ item }} state=started enabled=true
  ignore_errors: true
  with_items:
    - evm-watchdog
    - evmserverd
