  
---
- hosts: all
  remote_user: root
  become: yes
  become_method: sudo
  
  vars:
    ansible_ssh_pass: smartvm
    rhsm_username:
    rhsm_password:
    rhsm_pool_id:

  roles:
    - common
    - vddk
    - db
